spring.application.name=scheduling-api

spring.datasource.username=root
spring.datasource.password=123
spring.datasource.url=jdbc:mysql://localhost:5432/scheduling_db

spring.sql.init.mode=always
spring.sql.init.data-locations=populationScript.sql
