spring.application.name=scheduling-api

spring.datasource.username=root
spring.datasource.password=123
spring.datasource.url=jdbc:postgresql://localhost:5432/scheduling_db

spring.jpa.defer-datasource-initialization=true

spring.jpa.hibernate.ddl-auto=create
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:populationScript.sql


security.token.secret =${JWT_SECRET:my-secret-key}